export default [
    {
        id: 0,
        title:"축구공 공구",
        image: "https://i.postimg.cc/tT5w5HVn/football.jpg",
        category: 'Sporting Goods',
        price: '$49.99',
        name: 'Football',
        startdate: '21/08/10',
        finishdate: '21/08/15',
        status: "진행중",
        currentnum : 5,
        goalnum: 7,
        proposer:"hologachi1",
        site: "https://shop.adidas.co.kr/PF070801.action?pageNo=1709&NFN_ST=Y&gclid=CjwKCAjwxo6IBhBKEiwAXSYBswbFYlnFxJrRZx8mlcAl5tHkOGDDhcaD22c4gJynnvy60NhsKMw3zBoCyUAQAvD_BwE"
      },
      {
        id: 1,
        image: "https://i.postimg.cc/CL7k7w19/image.jpg",
        title:"아이폰 공구",
        category: 'Electronics',
        price: '$99.99',
        name: '아이폰 12 미니',
        startdate: '21/08/11',
        finishdate: '21/08/29',
        status: "모집중",
        currentnum : 5,
        goalnum: 7,
        proposer:"hologachi2",
        site:"https://www.apple.com/kr/"
      },
      {
        id: 2,
        image: "https://i.postimg.cc/tCjNDrzn/image.jpg",
        title:"신라면 공구",
        category: '식품',
        price: '$1.99',
        name: '신라면',
        startdate: '21/08/12',
        finishdate: '21/08/20',
        status: "모집중",
        currentnum : 5,
        goalnum: 7,
        proposer:"hologachi3",
        site: "https://www.lotteon.com/p/product/LM8801043014830?sitmNo=LM8801043014830_001&mall_no=4&dp_infw_cd=SCH%EC%8B%A0%EB%9D%BC%EB%A9%B4"
      },
      {
        id: 4,
        image: "https://i.postimg.cc/h4XM7YXx/image.png",
        title:"애플펜슬 공구",
        category: '전자제품',
        price: '$100',
        name: '애플펜슬',
        startdate: '21/08/13',
        finishdate: '21/08/14',
        status: "모집중",
        currentnum : 5,
        goalnum: 7,
        proposer:"hologachi4",
        site: "https://www.apple.com/kr/"
      },
]